# Generated by Django 5.0.3 on 2024-04-05 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_recipeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='image',
            new_name='recipe_image',
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_images', to='ledger.recipe'),
        ),
    ]
