# Generated by Django 5.0.3 on 2024-04-05 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_rename_image_recipeimage_recipe_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='recipe_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ledger.recipe'),
        ),
    ]
