# Generated by Django 5.0.3 on 2024-04-05 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_alter_recipeimage_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='image',
            new_name='recipe_image',
        ),
    ]
